export type ParamSpec = {
  name: string
  required?: boolean
  example?: string
  hint?: string
  value?: string
}

export type EndpointSpec = {
  id: string
  group: string
  method: "GET" | "POST" | "PUT" | "DELETE"
  path: string
  title: string
  description: string
  params?: ParamSpec[]
  query?: ParamSpec[]
  body?: {
    required?: boolean
    example: string
    hint?: string
  }
  auth?: string
  notes?: string[]
  public?: boolean
  uiHidden?: boolean
}

export type GroupSpec = {
  key: string
  title: string
  description: string
  basePath: string
}

export type CategorySpec = {
  key: string
  title: string
  groupKeys: string[]
}

const API_AUTH_LABEL = "Requires headers: x-api-token, x-api-username, x-api-password"
const API_HEADER_FIELDS = [
  { name: "x-api-token", label: "API Token" },
  { name: "x-api-username", label: "API Username" },
  { name: "x-api-password", label: "API Password" },
]

const getAuthLabel = (endpoint: EndpointSpec) => {
  if (endpoint.public) return endpoint.auth ?? "Public · No API headers required"
  return endpoint.auth ?? API_AUTH_LABEL
}

export const GROUPS: GroupSpec[] = [
  {
    key: "home",
    title: "Home",
    description: "Aggregated picks across drama, anime, movies, and manga.",
    basePath: "/api/home",
  },
  {
    key: "drama-providers",
    title: "Drama Providers",
    description: "Provider discovery endpoints for the drama stack.",
    basePath: "/api/drama",
  },
  {
    key: "dramabox",
    title: "Dramabox",
    description: "Drama catalog, details, genres, and streaming.",
    basePath: "/api/drama/dramabox",
  },
  {
    key: "melolo",
    title: "Melolo",
    description: "Recommendations, search, series details, and video streaming.",
    basePath: "/api/drama/melolo",
  },
  {
    key: "drama-v2",
    title: "Drama V2",
    description: "Combined Drama API v2 - Unified endpoints for Dramabox and Melolo with smart aggregation.",
    basePath: "/api/v2/drama",
  },
  {
    key: "movies",
    title: "Movies",
    description: "Provider discovery for movie integrations.",
    basePath: "/api/movies",
  },
  {
    key: "flixhq",
    title: "FlixHQ",
    description: "Recommendations, genres, details, and streaming.",
    basePath: "/api/movies/flixhq",
  },
  {
    key: "rebahin",
    title: "Rebahin",
    description: "Recommendations, genres, countries, details, search, and streaming.",
    basePath: "/api/movies/rebahin",
  },
  {
    key: "manga",
    title: "Manga Providers",
    description: "Provider discovery for manga integrations.",
    basePath: "/api/manga",
  },
  {
    key: "mangahere",
    title: "MangaHere",
    description: "Recommendations, rankings, details, and chapters.",
    basePath: "/api/manga/mangahere",
  },
  {
    key: "komikku",
    title: "Komikku",
    description: "Recommendations, rankings, details, chapters, search, and genres.",
    basePath: "/api/manga/komikku",
  },
  {
    key: "anime-providers",
    title: "Anime Providers",
    description: "Provider discovery endpoints for the anime stack.",
    basePath: "/api/anime",
  },
  {
    key: "animein",
    title: "Animein",
    description: "Recommendations, releases, search, genres, details, and streaming via Animein.",
    basePath: "/api/anime/animein",
  },
  {
    key: "samehadaku",
    title: "Samehadaku",
    description: "Recommendations, new releases, ongoing, search, genres, details, and streaming.",
    basePath: "/api/anime/samehadaku",
  },

  // {
  //   key: "tensei",
  //   title: "Tensei",
  //   description: "Recommendations, search, genres, details, and streaming.",
  //   basePath: "/api/anime/tensei",
  // },
  {
    key: "auth",
    title: "Auth",
    description: "Registration and login for user sessions.",
    basePath: "/api/auth",
  },
  {
    key: "google-oauth",
    title: "Google OAuth",
    description: "Google OAuth 2.0 authentication with Backend Callback and Frontend Callback modes. Supports stateless signed state parameter for CSRF protection. Uses session token exchange for cross-origin cookie handling.",
    basePath: "/api/auth/google",
  },
  {
    key: "user",
    title: "User",
    description: "User data, subscription management, and profile updates.",
    basePath: "/api/user",
  },
  {
    key: "user-feedback",
    title: "User Feedback",
    description: "Submit and manage user feedback, bug reports, and feature requests.",
    basePath: "/api/feedback",
  },
  // Catalog Groups
  {
    key: "catalog-categories",
    title: "Catalog: Categories",
    description: "Manage content categories for organizing drama, anime, movies, and manga.",
    basePath: "/api/catalog/category",
  },
  {
    key: "catalog-content-items",
    title: "Catalog: Content Items",
    description: "Manage content items that map provider content to categories.",
    basePath: "/api/catalog/content-item",
  },
  {
    key: "catalog-content-units",
    title: "Catalog: Content Units",
    description: "Manage episodes, chapters, and movies (units) within content items.",
    basePath: "/api/catalog/content-unit",
  },
  {
    key: "catalog-comments",
    title: "Catalog: Comments",
    description: "User comments and nested replies on content items.",
    basePath: "/api/catalog/comment",
  },
  {
    key: "catalog-favorites",
    title: "Catalog: Favorites",
    description: "User favorite content tracking.",
    basePath: "/api/catalog/whitelist",
  },
  {
    key: "movie-private",
    title: "Movie: Private",
    description: "Private provider for movie recommendations, ranking, details, and streaming.",
    basePath: "/api/movies/private",
  },
]

export const CATEGORY_SECTIONS: CategorySpec[] = [
  {
    key: "general",
    title: "General",
    groupKeys: ["home", "auth", "google-oauth", "user", "user-feedback"],
  },
  {
    key: "drama",
    title: "Drama",
    groupKeys: ["drama-providers", "dramabox", "melolo", "drama-v2"],
  },
  {
    key: "anime",
    title: "Anime",
    groupKeys: ["anime-providers", "animein", "samehadaku", "aniwatch"],
  },
  {
    key: "movies",
    title: "Movies",
    groupKeys: ["movies", "flixhq", "rebahin"],
  },
  {
    key: "manga",
    title: "Manga",
    groupKeys: ["manga", "mangahere", "komikku"],
  },
  {
    key: "catalog",
    title: "Catalog",
    groupKeys: ["catalog-categories", "catalog-content-items", "catalog-content-units", "catalog-comments", "catalog-favorites", "catalog-whitelist"],
  },
  {
    key: "private",
    title: "Private",
    groupKeys: ["movie-private"],
  },
]

const REBAHIN_NOTES = ["Handled by src/routes/movies/rebahin.route.ts -> src/controllers/movies/rebahin.controller.ts"]

const GROUP_MAP = Object.fromEntries(GROUPS.map((group) => [group.key, group])) as Record<string, GroupSpec>

export const ENDPOINTS: EndpointSpec[] = [
  {
    id: "home-aggregate",
    group: "home",
    method: "GET",
    path: "/api/home",
    title: "Homepage Aggregated Feed",
    description: "Get featured drama, anime, movies, and manga in one call.",
  },
  {
    id: "drama-providers",
    group: "drama-providers",
    method: "GET",
    path: "/api/drama/providers",
    title: "Drama Providers",
    description: "List available drama providers.",
  },
  {
    id: "dramabox-recommendations",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/recommendations",
    title: "Dramabox Recommendations",
    description: "Get a list of recommended dramas.",
    query: [{ name: "lang", example: "in", value: "in", hint: "Language code." }],
  },
  {
    id: "dramabox-new-release",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/new-release",
    title: "Latest Dramabox Releases",
    description: "Latest releases with pagination.",
    query: [
      { name: "lang", example: "in", value: "in" },
      { name: "page", example: "1", value: "1" },
      { name: "pageSize", example: "20", value: "20" },
    ],
  },
  {
    id: "dramabox-rank",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/rank",
    title: "Dramabox Ranking",
    description: "Drama rankings.",
    query: [
      { name: "lang", example: "in", value: "in" },
      { name: "page", example: "1", value: "1" },
      { name: "pageSize", example: "15", value: "15" },
    ],
  },
  {
    id: "dramabox-search",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/search",
    title: "Search Dramabox",
    description: "Search dramas by keyword.",
    query: [
      { name: "query", required: true, example: "love", value: "love" },
      { name: "lang", example: "in", value: "in" },
      { name: "page", example: "1", value: "1" },
      { name: "pageSize", example: "10", value: "10" },
    ],
  },
  {
    id: "dramabox-search-suggest",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/search-suggest",
    title: "Dramabox Search Suggestions",
    description: "Get suggestions by keyword.",
    query: [
      { name: "query", required: true, example: "boss", value: "boss" },
      { name: "lang", example: "in", value: "in" },
    ],
  },
  {
    id: "dramabox-genre",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/genre",
    title: "Dramabox Genres",
    description: "Available genres.",
    query: [{ name: "lang", example: "in", value: "in" }],
  },
  {
    id: "dramabox-genre-detail",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/genre/:id",
    title: "Dramabox Genre Details",
    description: "Dramas by genre.",
    params: [{ name: "id", required: true, hint: "Use id from /genre." }],
    query: [{ name: "lang", example: "in", value: "in" }],
  },
  {
    id: "dramabox-detail",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/detail/:id",
    title: "Dramabox Drama Details",
    description: "Drama details with chapters.",
    params: [{ name: "id", required: true, hint: "Use id from the drama list." }],
    query: [{ name: "lang", example: "in", value: "in" }],
  },
  {
    id: "dramabox-stream",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/stream/:id",
    title: "Dramabox Stream",
    description: "Stream the first episode.",
    params: [{ name: "id", required: true, hint: "Use id from drama details." }],
    query: [{ name: "lang", example: "in", value: "in" }],
  },
  {
    id: "dramabox-stream-chapter",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/stream/:id/:chapterIndex",
    title: "Dramabox Stream Chapter",
    description: "Stream a specific episode.",
    params: [
      { name: "id", required: true, hint: "Use id from drama details." },
      { name: "chapterIndex", required: true, example: "1", value: "1" },
    ],
    query: [{ name: "lang", example: "in", value: "in" }],
  },
  {
    id: "dramabox-languages",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/languages",
    title: "Dramabox Languages",
    description: "Available languages.",
  },
  {
    id: "dramabox-vip",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/vip",
    title: "Dramabox VIP",
    description: "VIP collections and highlights.",
    query: [{ name: "lang", example: "in", value: "in" }],
  },
  {
    id: "dramabox-all-chapters",
    group: "dramabox",
    method: "GET",
    path: "/api/drama/dramabox/get-all-chapters/:id",
    title: "Dramabox All Chapters",
    description: "Batch fetch stream URLs for every chapter of a title.",
    params: [{ name: "id", required: true, hint: "Use id from drama details." }],
    query: [{ name: "lang", example: "in", value: "in", hint: "Language code." }],
    notes: ["Returns chapterId, chapterIndex, chapterName, and streamUrl for each chapter."],
  },
  {
    id: "melolo-recommendations",
    group: "melolo",
    method: "GET",
    path: "/api/drama/melolo/recommendations",
    title: "Melolo Recommendations",
    description: "Combined latest and trending with offset.",
    query: [
      { name: "limit", example: "15", value: "15" },
      { name: "offset", example: "0", value: "0" },
    ],
  },
  {
    id: "melolo-new-release",
    group: "melolo",
    method: "GET",
    path: "/api/drama/melolo/new-release",
    title: "Latest Melolo Releases",
    description: "Latest releases.",
    query: [
      { name: "limit", example: "15", value: "15" },
      { name: "offset", example: "0", value: "0" },
    ],
  },
  {
    id: "melolo-rank",
    group: "melolo",
    method: "GET",
    path: "/api/drama/melolo/rank",
    title: "Melolo Ranking",
    description: "Trending list and ranking.",
    query: [
      { name: "limit", example: "15", value: "15" },
      { name: "offset", example: "0", value: "0" },
    ],
  },
  {
    id: "melolo-search",
    group: "melolo",
    method: "GET",
    path: "/api/drama/melolo/search",
    title: "Search Melolo Series",
    description: "Search series by keyword.",
    query: [
      { name: "query", required: true, example: "ceo", value: "ceo" },
      { name: "limit", example: "15", value: "15" },
      { name: "offset", example: "0", value: "0" },
    ],
  },
  {
    id: "melolo-search-suggest",
    group: "melolo",
    method: "GET",
    path: "/api/drama/melolo/search-suggest",
    title: "Melolo Search Suggestions",
    description: "Suggestions by keyword.",
    query: [
      { name: "query", required: true, example: "ceo", value: "ceo" },
      { name: "limit", example: "15", value: "15" },
      { name: "offset", example: "0", value: "0" },
    ],
  },
  {
    id: "melolo-detail",
    group: "melolo",
    method: "GET",
    path: "/api/drama/melolo/detail/:id",
    title: "Melolo Series Details",
    description: "Series details with chapters.",
    params: [{ name: "id", required: true, hint: "Use id from the Melolo list." }],
  },
  {
    id: "melolo-stream",
    group: "melolo",
    method: "GET",
    path: "/api/drama/melolo/stream/:id",
    title: "Melolo Stream",
    description: "Stream the main video.",
    params: [{ name: "id", required: true, hint: "Use id from series details." }],
  },
  {
    id: "melolo-stream-chapter",
    group: "melolo",
    method: "GET",
    path: "/api/drama/melolo/stream/:id/:chapterIndex",
    title: "Melolo Stream Chapter",
    description: "Stream a specific chapter.",
    params: [
      { name: "id", required: true, hint: "Use id from series details." },
      { name: "chapterIndex", required: true, example: "1", value: "1" },
    ],
  },
  {
    id: "movies-providers",
    group: "movies",
    method: "GET",
    path: "/api/movies/providers",
    title: "Movie Providers",
    description: "List available movie providers.",
  },
  {
    id: "flixhq-recommendations",
    group: "flixhq",
    method: "GET",
    path: "/api/movies/flixhq/recommendations",
    title: "FlixHQ Recommendations",
    description: "Trending picks from FlixHQ.",
  },
  {
    id: "flixhq-new-release",
    group: "flixhq",
    method: "GET",
    path: "/api/movies/flixhq/new-release",
    title: "FlixHQ Latest Releases",
    description: "Freshly released movies.",
  },
  {
    id: "flixhq-genre",
    group: "flixhq",
    method: "GET",
    path: "/api/movies/flixhq/genre",
    title: "FlixHQ Genres",
    description: "Available genres from FlixHQ.",
  },
  {
    id: "flixhq-genre-detail",
    group: "flixhq",
    method: "GET",
    path: "/api/movies/flixhq/genre/:id",
    title: "FlixHQ Genre Details",
    description: "Movies by genre.",
    query: [{ name: "id", required: true, example: "action", value: "action" }],
  },
  {
    id: "movie-private-recommendations",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/recommendations",
    title: "Private Recommendations",
    description: "Get movie recommendations for you.",
    uiHidden: true,
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
  },
  {
    id: "movie-private-new-release",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/new-release",
    title: "Private New Releases",
    description: "Get latest movie releases.",
    uiHidden: true,
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
  },
  {
    id: "movie-private-rank",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/rank",
    title: "Private Movie Ranking",
    description: "Get hottest movies ranking.",
    uiHidden: true,
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
  },
  {
    id: "movie-private-genre",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/genre",
    title: "Private Movie Genres",
    description: "Get list of movie genres.",
    uiHidden: true,
  },
  {
    id: "movie-private-country",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/country",
    title: "Private Movie Countries",
    description: "Get list of movie countries.",
    uiHidden: true,
  },
  {
    id: "movie-private-genre-detail",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/genre/:id",
    title: "Private Movies by Genre",
    description: "Get movies filtered by genre ID.",
    uiHidden: true,
    params: [{ name: "id", required: true, hint: "Genre name (e.g., Action)" }],
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
  },
  {
    id: "movie-private-country-detail",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/country/:id",
    title: "Private Movies by Country",
    description: "Get movies filtered by country name.",
    uiHidden: true,
    params: [{ name: "id", required: true, hint: "Country name (e.g., Korea)" }],
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
  },
  {
    id: "movie-private-detail",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/detail/:id",
    title: "Private Movie Details",
    description: "Get full movie details including casts and genre.",
    uiHidden: true,
    params: [{ name: "id", required: true, hint: "id from list." }],
  },
  {
    id: "movie-private-stream",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/stream/:id/:detailPath",
    title: "Private Movie Streaming",
    description: "Get stream URLs for a specific movie.",
    uiHidden: true,
    params: [
      { name: "id", required: true, hint: "id from detail." },
      { name: "detailPath", required: true, hint: "detailPath from detail." },
    ],
  },
  {
    id: "movie-private-captions",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/captions/:subtitleId/:id/:detailPath/:format",
    title: "Private Movie Captions",
    description: "Get captions/subtitles for the stream.",
    uiHidden: true,
    params: [
      { name: "subtitleId", required: true },
      { name: "id", required: true },
      { name: "detailPath", required: true },
      { name: "format", required: true, example: "vtt" },
    ],
  },
  {
    id: "flixhq-country",
    group: "flixhq",
    method: "GET",
    path: "/api/movies/flixhq/country",
    title: "FlixHQ Countries",
    description: "Available countries for filtering.",
  },
  {
    id: "flixhq-country-detail",
    group: "flixhq",
    method: "GET",
    path: "/api/movies/flixhq/country/:id",
    title: "FlixHQ Country Details",
    description: "Movies filtered by country.",
    params: [{ name: "id", required: true, example: "korea", value: "korea" }],
    query: [{ name: "page", example: "1", value: "1" }],
  },
  {
    id: "flixhq-detail",
    group: "flixhq",
    method: "GET",
    path: "/api/movies/flixhq/detail",
    title: "FlixHQ Details",
    description: "Movie details with episodes list.",
    query: [{ name: "id", required: true, example: "tt2395427", value: "tt2395427" }],
  },
  {
    id: "flixhq-stream",
    group: "flixhq",
    method: "GET",
    path: "/api/movies/flixhq/stream",
    title: "FlixHQ Stream",
    description: "Get stream sources for an episode.",
    query: [
      { name: "id", required: true, example: "tt2395427", value: "tt2395427" },
      { name: "chapterId", required: true, example: "episode-1", value: "episode-1" },
    ],
  },
  {
    id: "rebahin-recommendations",
    group: "rebahin",
    method: "GET",
    path: "/api/movies/rebahin/recommendations",
    title: "Rebahin Recommendations",
    description: "Recommended and spotlight movies from Rebahin.",
    notes: REBAHIN_NOTES,
    query: [
      { name: "page", example: "1", value: "1", hint: "Optional page number. Default 1." },
      { name: "limit", example: "30", value: "30", hint: "Optional page size. Default 30." },
    ],
  },
  {
    id: "rebahin-new-release",
    group: "rebahin",
    method: "GET",
    path: "/api/movies/rebahin/new-release",
    title: "Rebahin Latest Releases",
    description: "Latest movie releases on Rebahin.",
    notes: REBAHIN_NOTES,
    query: [
      { name: "page", example: "1", value: "1", hint: "Optional page number. Default 1." },
      { name: "limit", example: "30", value: "30", hint: "Optional page size. Default 30." },
    ],
  },
  {
    id: "rebahin-genre",
    group: "rebahin",
    method: "GET",
    path: "/api/movies/rebahin/genre",
    title: "Rebahin Genres",
    description: "Available genres from Rebahin.",
    notes: REBAHIN_NOTES,
  },
  {
    id: "rebahin-country",
    group: "rebahin",
    method: "GET",
    path: "/api/movies/rebahin/country",
    title: "Rebahin Countries",
    description: "Available countries for filtering.",
    notes: REBAHIN_NOTES,
  },
  {
    id: "rebahin-genre-detail",
    group: "rebahin",
    method: "GET",
    path: "/api/movies/rebahin/genre/:id",
    title: "Rebahin Genre Details",
    description: "Movies filtered by genre.",
    notes: REBAHIN_NOTES,
    params: [{ name: "id", required: true, hint: "Genre ID from /genre." }],
    query: [
      { name: "page", example: "1", value: "1", hint: "Optional page number. Default 1." },
      { name: "limit", example: "30", value: "30", hint: "Optional page size. Default 30." },
    ],
  },
  {
    id: "rebahin-country-detail",
    group: "rebahin",
    method: "GET",
    path: "/api/movies/rebahin/country/:id",
    title: "Rebahin Country Details",
    description: "Movies filtered by country.",
    notes: REBAHIN_NOTES,
    params: [{ name: "id", required: true, hint: "Country ID from /country." }],
    query: [
      { name: "page", example: "1", value: "1", hint: "Optional page number. Default 1." },
      { name: "limit", example: "30", value: "30", hint: "Optional page size. Default 30." },
    ],
  },
  {
    id: "rebahin-detail",
    group: "rebahin",
    method: "GET",
    path: "/api/movies/rebahin/detail/:id",
    title: "Rebahin Details",
    description: "Movie details with episodes/embeds list.",
    notes: REBAHIN_NOTES,
    params: [{ name: "id", required: true, hint: "Use id from recommendations, genre, country, or search." }],
  },
  {
    id: "rebahin-stream",
    group: "rebahin",
    method: "GET",
    path: "/api/movies/rebahin/stream/:id",
    title: "Rebahin Stream",
    description: "Get streaming embeds for a movie.",
    notes: REBAHIN_NOTES,
    params: [{ name: "id", required: true, hint: "Movie id from details." }],
  },
  {
    id: "rebahin-search",
    group: "rebahin",
    method: "GET",
    path: "/api/movies/rebahin/search",
    title: "Search Rebahin",
    description: "Search movies by keyword.",
    notes: REBAHIN_NOTES,
    query: [
      { name: "query", required: true, example: "action", value: "action" },
      { name: "page", example: "1", value: "1", hint: "Optional page number. Default 1." },
      { name: "limit", example: "30", value: "30", hint: "Optional page size. Default 30." },
    ],
  },
  {
    id: "manga-providers",
    group: "manga",
    method: "GET",
    path: "/api/manga/providers",
    title: "Manga Providers",
    description: "List available manga providers.",
  },
  {
    id: "mangahere-recommendations",
    group: "mangahere",
    method: "GET",
    path: "/api/manga/mangahere/recommendations",
    title: "MangaHere Recommendations",
    description: "Hot picks and featured titles.",
  },
  {
    id: "mangahere-rank",
    group: "mangahere",
    method: "GET",
    path: "/api/manga/mangahere/rank",
    title: "MangaHere Rank",
    description: "Ranking list from MangaHere.",
  },
  {
    id: "mangahere-new-release",
    group: "mangahere",
    method: "GET",
    path: "/api/manga/mangahere/new-release",
    title: "MangaHere Latest Releases",
    description: "Recent manga releases.",
    query: [{ name: "page", example: "1", value: "1" }],
  },
  {
    id: "mangahere-detail",
    group: "mangahere",
    method: "GET",
    path: "/api/manga/mangahere/detail/:id",
    title: "MangaHere Details",
    description: "Manga details with chapters.",
    params: [{ name: "id", required: true, hint: "Use id from manga list or search." }],
  },
  {
    id: "mangahere-search",
    group: "mangahere",
    method: "GET",
    path: "/api/manga/mangahere/search",
    title: "Search MangaHere",
    description: "Search manga by keyword.",
    query: [{ name: "query", required: true, example: "solo leveling", value: "solo leveling" }],
  },
  {
    id: "mangahere-chapters",
    group: "mangahere",
    method: "GET",
    path: "/api/manga/mangahere/chapters",
    title: "MangaHere Chapter Pages",
    description: "Fetch pages for a chapter.",
    query: [{ name: "id", required: true, example: "chapter-1", value: "chapter-1" }],
  },
  {
    id: "komikku-recommendations",
    group: "komikku",
    method: "GET",
    path: "/api/manga/komikku/recommendations",
    title: "Komikku Recommendations",
    description: "Homepage recommendations.",
  },
  {
    id: "komikku-rank",
    group: "komikku",
    method: "GET",
    path: "/api/manga/komikku/rank",
    title: "Komikku Rank",
    description: "Ranking list from Komikku.",
  },
  {
    id: "komikku-new-release",
    group: "komikku",
    method: "GET",
    path: "/api/manga/komikku/new-release",
    title: "Komikku Latest Releases",
    description: "Recent manga releases from Komikku.",
  },
  {
    id: "komikku-detail",
    group: "komikku",
    method: "GET",
    path: "/api/manga/komikku/detail/:id",
    title: "Komikku Details",
    description: "Manga details with chapters.",
    params: [{ name: "id", required: true, hint: "Use id from recommendations, rank, or search." }],
  },
  {
    id: "komikku-search",
    group: "komikku",
    method: "GET",
    path: "/api/manga/komikku/search",
    title: "Search Komikku",
    description: "Search manga by keyword.",
    query: [
      { name: "query", required: true, example: "solo leveling", value: "solo leveling" },
      { name: "page", example: "1", value: "1", hint: "Optional page number." },
    ],
  },
  {
    id: "komikku-chapters",
    group: "komikku",
    method: "GET",
    path: "/api/manga/komikku/chapters",
    title: "Komikku Chapter Pages",
    description: "Fetch pages for a Komikku chapter.",
    query: [{ name: "id", required: true, example: "chapter-1", value: "chapter-1" }],
  },
  {
    id: "komikku-genres",
    group: "komikku",
    method: "GET",
    path: "/api/manga/komikku/genre",
    title: "Komikku Genres",
    description: "Available genres from Komikku.",
  },
  {
    id: "anime-providers",
    group: "anime-providers",
    method: "GET",
    path: "/api/anime/providers",
    title: "Anime Providers",
    description: "List available anime providers.",
  },
  {
    id: "animein-recommendations",
    group: "animein",
    method: "GET",
    path: "/api/anime/animein/recommendations",
    title: "Animein Recommendations",
    description: "Homepage popular picks.",
    query: [{ name: "limit", example: "50", value: "50", hint: "Optional limit. Defaults to 50." }],
  },
  {
    id: "animein-new-release",
    group: "animein",
    method: "GET",
    path: "/api/anime/animein/new-release",
    title: "Animein Latest Releases",
    description: "Latest releases with pagination.",
    query: [{ name: "limit", example: "50", value: "50", hint: "Optional limit. Defaults to 50." }],
  },
  {
    id: "animein-rank",
    group: "animein",
    method: "GET",
    path: "/api/anime/animein/rank",
    title: "Animein Ranking",
    description: "Trending list and ranking.",
    query: [{ name: "limit", example: "50", value: "50", hint: "Optional limit. Defaults to 50." }],
  },
  {
    id: "animein-search",
    group: "animein",
    method: "GET",
    path: "/api/anime/animein/search",
    title: "Search Animein",
    description: "Search anime by keyword.",
    query: [
      { name: "query", required: true, example: "naruto", value: "naruto" },
      { name: "page", example: "1", value: "1", hint: "Optional page number. Defaults to 1." },
    ],
  },
  {
    id: "animein-detail",
    group: "animein",
    method: "GET",
    path: "/api/anime/animein/detail/:id",
    title: "Animein Details",
    description: "Anime details with episodes.",
    params: [{ name: "id", required: true, hint: "Use id from search results." }],
  },
  {
    id: "animein-stream",
    group: "animein",
    method: "GET",
    path: "/api/anime/animein/stream/:episodeId",
    title: "Animein Stream",
    description: "Stream an episode by id.",
    params: [{ name: "episodeId", required: true, hint: "Use episode id from details." }],
  },
  {
    id: "animein-genre",
    group: "animein",
    method: "GET",
    path: "/api/anime/animein/genre",
    title: "Animein Genres",
    description: "List available genres.",
  },
  {
    id: "animein-genre-detail",
    group: "animein",
    method: "GET",
    path: "/api/anime/animein/genre/:id",
    title: "Animein Genre Titles",
    description: "Fetch titles for a specific genre.",
    params: [{ name: "id", required: true, hint: "Genre id from /genre." }],
    query: [{ name: "page", example: "1", value: "1", hint: "Optional page number. Defaults to 1." }],
  },




  // {
  //   id: "tensei-recommendations",
  //   group: "tensei",
  //   method: "GET",
  //   path: "/api/anime/tensei/recommendations",
  //   title: "Tensei Recommendations",
  //   description: "Popular/spotlight list.",
  //   query: [{ name: "page", example: "1", value: "1" }],
  // },
  // {
  //   id: "tensei-new-release",
  //   group: "tensei",
  //   method: "GET",
  //   path: "/api/anime/tensei/new-release",
  //   title: "Tensei Latest Releases",
  //   description: "Latest releases with pagination.",
  //   query: [{ name: "page", example: "1", value: "1" }],
  // },
  // {
  //   id: "tensei-rank",
  //   group: "tensei",
  //   method: "GET",
  //   path: "/api/anime/tensei/rank",
  //   title: "Tensei Ranking",
  //   description: "Ranking list.",
  //   query: [{ name: "page", example: "1", value: "1" }],
  // },
  // {
  //   id: "tensei-search",
  //   group: "tensei",
  //   method: "GET",
  //   path: "/api/anime/tensei/search",
  //   title: "Search Tensei",
  //   description: "Search anime by keyword.",
  //   query: [{ name: "query", required: true, example: "naruto", value: "naruto" }],
  // },
  // {
  //   id: "tensei-genre",
  //   group: "tensei",
  //   method: "GET",
  //   path: "/api/anime/tensei/genre",
  //   title: "Tensei Genres",
  //   description: "Available genres.",
  // },
  // {
  //   id: "tensei-genre-detail",
  //   group: "tensei",
  //   method: "GET",
  //   path: "/api/anime/tensei/genre/:id",
  //   title: "Tensei Genre Details",
  //   description: "Anime by genre.",
  //   params: [{ name: "id", required: true, example: "action", value: "action" }],
  //   query: [{ name: "page", example: "1", value: "1" }],
  // },
  // {
  //   id: "tensei-detail",
  //   group: "tensei",
  //   method: "GET",
  //   path: "/api/anime/tensei/detail/:id",
  //   title: "Tensei Details",
  //   description: "Anime details with episodes.",
  //   params: [{ name: "id", required: true, hint: "Use id from search or genre list." }],
  // },
  // {
  //   id: "tensei-stream",
  //   group: "tensei",
  //   method: "GET",
  //   path: "/api/anime/tensei/stream/:id",
  //   title: "Tensei Stream",
  //   description: "Stream an episode by id.",
  //   params: [{ name: "id", required: true, hint: "Use episode id from details." }],
  // },
  // Samehadaku Endpoints
  {
    id: "samehadaku-recommendations",
    group: "samehadaku",
    method: "GET",
    path: "/api/anime/samehadaku/recommendations",
    title: "Samehadaku Recommendations",
    description: "Get recommended/popular anime from Samehadaku.",
    query: [
      { name: "page", example: "1", value: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "20", value: "20", hint: "Items per page. Default: 20, Max: 100" },
    ],
    notes: ["Response: { success, source, path, count, data: [{ id, title, coverImage, chapterCount }] }"],
  },
  {
    id: "samehadaku-new-release",
    group: "samehadaku",
    method: "GET",
    path: "/api/anime/samehadaku/new-release",
    title: "Samehadaku New Releases",
    description: "Get latest anime releases from Samehadaku.",
    query: [
      { name: "page", example: "1", value: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "20", value: "20", hint: "Items per page. Default: 20, Max: 100" },
    ],
    notes: ["Response: { success, source, path, count, data: [{ id, title, coverImage, chapterCount }] }"],
  },
  {
    id: "samehadaku-ongoing",
    group: "samehadaku",
    method: "GET",
    path: "/api/anime/samehadaku/ongoing",
    title: "Samehadaku Ongoing",
    description: "Get ongoing anime series from Samehadaku.",
    query: [
      { name: "page", example: "1", value: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "20", value: "20", hint: "Items per page. Default: 20, Max: 100" },
    ],
    notes: ["Response: { success, source, path, count, data: [{ id, title, coverImage, chapterCount }] }"],
  },
  {
    id: "samehadaku-search",
    group: "samehadaku",
    method: "GET",
    path: "/api/anime/samehadaku/search",
    title: "Search Samehadaku",
    description: "Search anime by keyword.",
    query: [
      { name: "query", required: true, example: "naruto", value: "naruto", hint: "Search keyword" },
      { name: "page", example: "1", value: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "20", value: "20", hint: "Items per page. Default: 20, Max: 100" },
    ],
    notes: ["Response: { success, source, path, count, query, data: [{ id, title, coverImage }] }"],
  },
  {
    id: "samehadaku-genre",
    group: "samehadaku",
    method: "GET",
    path: "/api/anime/samehadaku/genre",
    title: "Samehadaku Genres",
    description: "List all available anime genres.",
    notes: ["Response: { success, source, path, count, data: [{ genreId, genre, slug, count }] }"],
  },
  {
    id: "samehadaku-genre-detail",
    group: "samehadaku",
    method: "GET",
    path: "/api/anime/samehadaku/genre/:genreId",
    title: "Samehadaku Genre Details",
    description: "Get anime by genre ID or slug.",
    params: [{ name: "genreId", required: true, example: "action", value: "action", hint: "Genre ID or slug from /genre" }],
    query: [
      { name: "page", example: "1", value: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "20", value: "20", hint: "Items per page. Default: 20, Max: 100" },
    ],
    notes: ["Response: { success, source, path, count, data: [{ id, title, coverImage }] }"],
  },
  {
    id: "samehadaku-detail",
    group: "samehadaku",
    method: "GET",
    path: "/api/anime/samehadaku/detail/:id",
    title: "Samehadaku Details",
    description: "Get anime details with episode list.",
    params: [{ name: "id", required: true, example: "1234", value: "1234", hint: "Anime ID (numeric) or slug" }],
    notes: [
      "Accepts numeric ID, category ID, or slug",
      "Response: { success, source, path, resolvedBy, episodeCount, data: { id, title, description, coverImage, chapterCount, chapters: [{ episodeId, chapterIndex }] } }"
    ],
  },
  {
    id: "samehadaku-stream",
    group: "samehadaku",
    method: "GET",
    path: "/api/anime/samehadaku/stream/:episodeId",
    title: "Samehadaku Stream",
    description: "Get stream sources for an episode.",
    params: [{ name: "episodeId", required: true, example: "48504", value: "48504", hint: "Episode ID (numeric) from details" }],
    notes: [
      "Response: { success, source, path, data: { id, title, coverImage, streamUrl, servers: [{ name, quality, streamUrl }] } }"
    ],
  },
  {
    id: "auth-register",
    group: "auth",
    method: "POST",
    path: "/api/auth/register",
    title: "Register",
    description: "Create a new account.",
    body: {
      required: true,
      example: `{
  "username": "demo",
  "email": "demo@example.com",
  "password": "secret123"
}`,
      hint: "Required: username, email, password.",
    },
  },
  {
    id: "auth-login",
    group: "auth",
    method: "POST",
    path: "/api/auth/login",
    title: "Login",
    description: "Log in and set the sid cookie.",
    body: {
      required: true,
      example: `{
  "username": "demo",
  "password": "secret123"
}`,
      hint: "The sid cookie is set on success.",
    },
  },
  {
    id: "auth-get-token",
    group: "auth",
    method: "GET",
    path: "/api/auth/get-token",
    title: "Get API Token",
    description: "Exchange username/password for an API token via query params. Does not require existing API key.",
    query: [
      { name: "username", required: true, example: "demo", hint: "Username untuk login." },
      { name: "password", required: true, example: "secret123", hint: "Password untuk login." },
    ],
    public: false,
    notes: ["Public bootstrap endpoint. Token expires after 1 hour; refresh as needed."],
  },
  {
    id: "auth-logout",
    group: "auth",
    method: "POST",
    path: "/api/auth/logout",
    title: "Logout",
    description: "Clear the session cookie and delete the session from the database.",
    public: false,
    notes: [
      "Requires 'sid' cookie to be present.",
      "Sets the 'sid' cookie with Max-Age=0 to clear it.",
      "Response: { message: 'Logged out' }"
    ],
  },
  // ============================================
  // Google OAuth - Backend Callback Mode
  // ============================================
  // FLOW: Frontend → /auth/google → Google → /auth/google/callback → Frontend?oauth_token=xxx → /auth/google/session-exchange → Cookie Set
  {
    id: "google-oauth-login",
    group: "google-oauth",
    method: "GET",
    path: "/api/auth/google",
    title: "Google OAuth - Initiate (Backend Callback Mode)",
    description: "Start Google OAuth flow. Returns authorization URL that redirects to backend callback.",
    query: [
      { name: "redirect", required: false, example: "http://localhost:3000/dashboard", hint: "URL to redirect after successful login (default: FRONTEND_URL env)" },
      { name: "format", required: false, example: "json", hint: "Response format: 'json' or 'redirect'. Default: 'json'" },
    ],
    public: true,
    notes: [
      "Flow: Frontend → /auth/google → Google → /auth/google/callback → Frontend?oauth_token=xxx → POST /session-exchange",
      "State parameter is signed with HMAC (stateless, no cookie needed)",
      "After Google login, backend redirects to frontend with temporary oauth_token",
      "Frontend must exchange the token via POST /auth/google/session-exchange to get the session cookie",
      "Cookie is set with SameSite=None for cross-origin support (requires HTTPS)",
      "Response (200 OK): { message: 'Google OAuth initiated', data: { authUrl, mode: 'backend', redirectAfterLogin } }",
    ],
  },
  {
    id: "google-oauth-callback",
    group: "google-oauth",
    method: "GET",
    path: "/api/auth/google/callback",
    title: "Google OAuth - Backend Callback",
    description: "Handle OAuth callback from Google (Backend Callback Mode). Exchanges code for user info and generates temporary token for session exchange.",
    query: [
      { name: "code", required: true, example: "4/0A...", hint: "Authorization code from Google" },
      { name: "state", required: true, example: "eyJ0...", hint: "Signed state parameter (contains redirect URL and timestamp)" },
      { name: "error", required: false, example: "access_denied", hint: "Error from Google if user denied access" },
    ],
    public: true,
    notes: [
      "This endpoint is called by Google after user login",
      "State is verified using HMAC signature (no cookie needed)",
      "If user not exists, auto-create with Google profile data",
      "Generates temporary oauth_token (valid 5 minutes, single-use)",
      "If browser request (Accept: text/html), redirects to ?oauth_token=xxx",
      "Cookie CANNOT be set on cross-origin redirect - use /session-exchange",
      "Response (200 Redirect): Location: redirectTo?oauth_token=temp_token",
      "Response (200 OK JSON): { message: 'Google login successful', data: { user, redirectTo } }",
      "Error (403): { message: 'Invalid state: ...' }",
      "Error (400): { message: 'Missing authorization code or state' }",
    ],
  },
  {
    id: "google-oauth-session-exchange",
    group: "google-oauth",
    method: "POST",
    path: "/api/auth/google/session-exchange",
    title: "Google OAuth - Exchange Session Token",
    description: "Exchange temporary oauth_token for session cookie. Call this from frontend after backend callback redirect.",
    body: {
      required: true,
      example: `{
  "token": "abc123def456..."
}`,
      hint: "Token from URL query param: ?oauth_token=xxx",
    },
    public: true,
    notes: [
      "Call this endpoint after receiving oauth_token from backend callback redirect",
      "Token is valid for 5 minutes and can only be used once",
      "Sets 'sid' session cookie (httpOnly, secure, SameSite=None, 7 days)",
      "Response (200 OK): { message: 'Session created successfully', data: { user: { id, username, email, displayName, avatarUrl } } }",
      "Error (400): { message: 'Invalid or expired token' }",
      "Important: Include credentials: 'include' in fetch request",
    ],
  },
  // ============================================
  // Google OAuth - Frontend Callback Mode (Recommended)
  // ============================================
  {
    id: "google-oauth-frontend",
    group: "google-oauth",
    method: "GET",
    path: "/api/auth/google/frontend",
    title: "Google OAuth - Initiate (Frontend Callback Mode)",
    description: "Start Google OAuth flow for Frontend Callback mode. Google redirects to frontend instead of backend. RECOMMENDED for production.",
    query: [
      { name: "callback_url", required: false, example: "http://localhost:3000/auth/callback", hint: "Frontend callback URL (must be registered in Google Console)" },
    ],
    public: true,
    notes: [
      "Flow: Frontend → Google → Frontend callback → POST /auth/google/exchange → Response with cookie",
      "RECOMMENDED for production - simpler flow without token exchange",
      "The callback_url must be registered in Google Cloud Console authorized redirect URIs",
      "Response (200 OK): { message: 'Google OAuth initiated', data: { authUrl, mode: 'frontend', callbackUrl } }",
    ],
  },
  {
    id: "google-oauth-exchange",
    group: "google-oauth",
    method: "POST",
    path: "/api/auth/google/exchange",
    title: "Google OAuth - Exchange Code (Frontend Callback Mode)",
    description: "Exchange authorization code for user info and session (Frontend Callback Mode).",
    body: {
      required: true,
      example: `{
  "code": "4/0Adeu...",
  "redirect_uri": "http://localhost:3000/auth/callback"
}`,
      hint: "code: from Google callback URL query param. redirect_uri: same as used in /auth/google/frontend",
    },
    public: true,
    notes: [
      "Call this endpoint from your frontend callback handler",
      "The code is obtained from Google redirect URL: ?code=xxx&state=yyy",
      "Backend exchanges code for access token with Google",
      "If user not exists, auto-create with Google profile data",
      "Sets 'sid' session cookie (httpOnly, secure, SameSite=None for cross-origin, 7 days)",
      "Response (200 OK): { message: 'Google login successful', data: { user: { id, username, email, displayName, avatarUrl } } }",
      "Error (400): { message: 'Failed to exchange authorization code' }",
      "Important: Include credentials: 'include' in fetch request to receive cookie",
    ],
  },
  // ============================================
  // Google OAuth - User Management
  // ============================================
  {
    id: "google-oauth-me",
    group: "google-oauth",
    method: "GET",
    path: "/api/auth/google/me",
    title: "Google OAuth - Get Current User",
    description: "Get current authenticated user info from Google OAuth session.",
    public: false,
    auth: "Requires 'sid' cookie from Google login.",
    notes: [
      "Returns current user info from session",
      "Session valid for 7 days",
      "Cookie is sent automatically if same-origin or with proper CORS settings",
      "Response (200 OK): { message: 'User info retrieved', data: { user: { id, username, email, displayName, avatarUrl, isActive, createdAt, updatedAt } } }",
      "Error (401): { message: 'Unauthorized' } (no session cookie)",
      "Error (401): { message: 'Session expired or invalid' }",
    ],
  },
  {
    id: "google-oauth-logout",
    group: "google-oauth",
    method: "POST",
    path: "/api/auth/google/logout",
    title: "Google OAuth - Logout",
    description: "Logout and destroy Google OAuth session.",
    public: false,
    auth: "Requires 'sid' cookie.",
    notes: [
      "Destroys session in database",
      "Clears 'sid' cookie",
      "Response (200 OK): { message: 'Logged out successfully' }",
      "Error (500): { message: 'Error during logout', error: {...} }",
    ],
  },
  {
    id: "user-get",
    group: "user",
    method: "GET",
    path: "/api/user/get",
    title: "List users",
    description: "Fetch user data (requires session).",
    auth: "API headers + sid cookie from login.",
  },
  {
    id: "user-delete",
    group: "user",
    method: "DELETE",
    path: "/api/user/delete/:id",
    title: "Delete user",
    description: "Delete a user by id.",
    params: [{ name: "id", required: true }],
    auth: "API headers + sid cookie from login.",
  },
  {
    id: "user-me",
    group: "user",
    method: "GET",
    path: "/api/user/me",
    title: "Get current user",
    description: "Fetch current authenticated user profile data.",
    auth: "Requires sid cookie from login.",
    notes: ["Returns: { message, data: { id, username, email, displayName, avatarUrl, isActive, createdAt, updatedAt } }"],
  },
  {
    id: "user-update",
    group: "user",
    method: "PUT",
    path: "/api/user/update/:id",
    title: "Update user",
    description: "Update user profile fields (username, email, displayName, avatarUrl, isActive).",
    params: [{ name: "id", required: true, hint: "User ID to update" }],
    body: {
      required: false,
      example: `{
  "username": "new_username",
  "email": "new@example.com",
  "displayName": "New Display Name",
  "avatarUrl": "https://example.com/avatar.jpg",
  "isActive": 1
}`,
    },
    auth: "Requires sid cookie from login.",
    notes: ["At least one field required", "Returns: { message, data: updatedUser }", "Error 409 if username/email already exists"],
  },
  {
    id: "user-update-password",
    group: "user",
    method: "PUT",
    path: "/api/user/update-password",
    title: "Update password",
    description: "Change user password after verifying current password.",
    body: {
      required: true,
      example: `{
  "currentPassword": "old_password",
  "newPassword": "new_secure_password"
}`,
    },
    auth: "Requires sid cookie from login.",
    notes: ["Returns: { message: 'Password changed!' }", "Error 400 if current password doesn't match"],
  },
  {
    id: "user-subscription-status",
    group: "user",
    method: "GET",
    path: "/api/user/subscription/status",
    title: "Check subscription status",
    description: "Get current user's subscription status including days remaining.",
    auth: "Requires sid cookie from login.",
    notes: [
      "Returns: { message, data: { isFree, isSubscribed, subscriptionType, subscriptionStart, subscriptionEnd, daysRemaining } }",
      "isSubscribed is true when isFree=false and subscriptionEnd is in the future",
      "daysRemaining shows days until subscription expires (null if not subscribed)",
    ],
  },
  {
    id: "user-subscription-update",
    group: "user",
    method: "PUT",
    path: "/api/user/subscription/:id",
    title: "Update user subscription",
    description: "Update user subscription details (admin or payment webhook use).",
    params: [{ name: "id", required: true, hint: "User ID to update subscription" }],
    body: {
      required: true,
      example: `{
  "isFree": false,
  "subscriptionType": "premium",
  "subscriptionStart": "2025-02-25T00:00:00Z",
  "subscriptionEnd": "2025-03-25T00:00:00Z"
}`,
      hint: "Fields: isFree (boolean), subscriptionType (string), subscriptionStart/end (ISO date strings)",
    },
    auth: "Requires sid cookie from login (admin recommended).",
    notes: [
      "At least one subscription field required",
      "Returns: { message, data: { id, isFree, subscriptionType, subscriptionStart, subscriptionEnd } }",
      "Use this for payment webhooks or admin subscription management",
    ],
  },
  // User Feedback Endpoints
  {
    id: "feedback-create",
    group: "user-feedback",
    method: "POST",
    path: "/api/feedback",
    title: "Create Feedback",
    description: "Submit new feedback, bug report, or feature request.",
    body: {
      required: true,
      example: `{
  "title": "Bug Report: Video Not Playing",
  "content": "When I try to play episode 5 of Drama X, the video keeps buffering...",
  "category": "bug",
  "rating": 4
}`,
      hint: "Required: title (3-200 chars), content (10-5000 chars). Optional: category (general|bug|feature|improvement), rating (1-5)",
    },
    auth: "Requires sid cookie from login.",
    notes: [
      "Returns: { message, data: { id, userId, title, content, category, rating, status, createdAt, updatedAt, user } }",
      "Status is automatically set to 'pending'",
      "User can only update feedback while status is 'pending'",
    ],
  },
  {
    id: "feedback-list",
    group: "user-feedback",
    method: "GET",
    path: "/api/feedback",
    title: "List All Feedbacks",
    description: "Fetch all feedbacks with filters and pagination (admin view).",
    query: [
      { name: "page", example: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "20", hint: "Items per page. Default: 20" },
      { name: "status", example: "pending", hint: "Filter by status: pending|in_progress|resolved|rejected" },
      { name: "category", example: "bug", hint: "Filter by category: general|bug|feature|improvement" },
      { name: "userId", example: "clxxx123", hint: "Filter by specific user ID" },
    ],
    auth: "Requires sid cookie from login (admin recommended).",
    notes: [
      "Returns: { message, data: [...], pagination: { page, limit, total, totalPages, hasMore } }",
      "Results include user details for each feedback",
    ],
  },
  {
    id: "feedback-my",
    group: "user-feedback",
    method: "GET",
    path: "/api/feedback/my",
    title: "My Feedbacks",
    description: "Get current user's submitted feedbacks with pagination.",
    query: [
      { name: "page", example: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "20", hint: "Items per page. Default: 20" },
      { name: "status", example: "pending", hint: "Filter by status: pending|in_progress|resolved|rejected" },
    ],
    auth: "Requires sid cookie from login.",
    notes: [
      "Returns: { message, data: [...], pagination: { page, limit, total, totalPages, hasMore } }",
      "Only returns feedbacks submitted by the current user",
    ],
  },
  {
    id: "feedback-get",
    group: "user-feedback",
    method: "GET",
    path: "/api/feedback/:id",
    title: "Get Feedback by ID",
    description: "Fetch a single feedback by ID with user details.",
    params: [{ name: "id", required: true, hint: "Feedback ID" }],
    auth: "Requires sid cookie from login.",
    notes: [
      "Returns: { message, data: { id, userId, title, content, category, rating, status, adminReply, createdAt, updatedAt, resolvedAt, user } }",
      "404 if feedback not found",
    ],
  },
  {
    id: "feedback-update",
    group: "user-feedback",
    method: "PUT",
    path: "/api/feedback/:id",
    title: "Update Feedback",
    description: "Update own feedback (only while status is 'pending').",
    params: [{ name: "id", required: true, hint: "Feedback ID to update" }],
    body: {
      required: true,
      example: `{
  "title": "Updated Title",
  "content": "Updated content with more details...",
  "category": "bug",
  "rating": 5
}`,
      hint: "Fields: title, content, category, rating. At least one field required.",
    },
    auth: "Requires sid cookie from login.",
    notes: [
      "Returns: { message, data: updatedFeedback }",
      "403 if user doesn't own the feedback",
      "400 if feedback status is not 'pending' (already being processed)",
    ],
  },
  {
    id: "feedback-delete",
    group: "user-feedback",
    method: "DELETE",
    path: "/api/feedback/:id",
    title: "Delete Feedback",
    description: "Delete own feedback.",
    params: [{ name: "id", required: true, hint: "Feedback ID to delete" }],
    auth: "Requires sid cookie from login.",
    notes: [
      "Returns: { message: 'Feedback deleted successfully' }",
      "403 if user doesn't own the feedback",
    ],
  },
  {
    id: "feedback-admin-update",
    group: "user-feedback",
    method: "PUT",
    path: "/api/feedback/admin/:id",
    title: "Admin Update Feedback",
    description: "Update feedback status and admin reply (admin only).",
    params: [{ name: "id", required: true, hint: "Feedback ID to update" }],
    body: {
      required: true,
      example: `{
  "status": "resolved",
  "adminReply": "Thank you for your feedback! The issue has been fixed."
}`,
      hint: "Fields: status (pending|in_progress|resolved|rejected), adminReply (string). At least one required.",
    },
    auth: "Requires sid cookie from login (admin only).",
    notes: [
      "Returns: { message, data: updatedFeedback }",
      "resolvedAt is automatically set when status changes to 'resolved'",
    ],
  },
  {
    id: "feedback-stats",
    group: "user-feedback",
    method: "GET",
    path: "/api/feedback/stats",
    title: "Feedback Statistics",
    description: "Get feedback statistics for admin dashboard.",
    auth: "Requires sid cookie from login (admin only).",
    notes: [
      "Returns: { message, data: { total, byStatus: { pending, inProgress, resolved, rejected }, byCategory: [...], resolutionRate } }",
      "resolutionRate is percentage of resolved feedbacks",
    ],
  },
  // Catalog - Comments
  {
    id: "catalog-comment-list",
    group: "catalog-comments",
    method: "GET",
    path: "/api/catalog/comment/all",
    title: "List Comments",
    description: "Fetch all comments with nested children (replies), content item, and user details.",
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, count, data: [{ id, userId, contentItemId, parentCommentId, body, isDeleted, createdAt, updatedAt, children, contentItem, user }] }"],
  },
  {
    id: "catalog-comment-create",
    group: "catalog-comments",
    method: "POST",
    path: "/api/catalog/comment/create",
    title: "Create Comment",
    description: "Create a new comment on a content item. Set parentCommentId to reply to another comment.",
    body: {
      required: true,
      example: `{
  "userId": "clxxx123",
  "contentItemId": "clxxx456",
  "body": "Great episode! Loved the plot twist.",
  "parentCommentId": null
}`,
      hint: "Required: userId, contentItemId, body. Optional: parentCommentId (set to comment ID for replies).",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, userId, contentItemId, parentCommentId, body, isDeleted, createdAt, updatedAt } }"],
  },
  {
    id: "catalog-comment-update",
    group: "catalog-comments",
    method: "PUT",
    path: "/api/catalog/comment/update/:id",
    title: "Update Comment",
    description: "Update an existing comment body or soft-delete status.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Comment ID to update." }],
    body: {
      required: true,
      example: `{
  "body": "Updated comment text",
  "isDeleted": 0
}`,
      hint: "Fields: body, isDeleted. At least one field required.",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, userId, contentItemId, parentCommentId, body, isDeleted, createdAt, updatedAt } }"],
  },
  {
    id: "catalog-comment-delete",
    group: "catalog-comments",
    method: "DELETE",
    path: "/api/catalog/comment/delete/:id",
    title: "Delete Comment",
    description: "Soft delete a comment by id. Sets isDeleted=1 to preserve thread integrity (replies remain visible).",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Comment ID to soft delete." }],
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, deletedId, data: { id, isDeleted } }"],
  },
  {
    id: "catalog-comment-get-replies",
    group: "catalog-comments",
    method: "GET",
    path: "/api/catalog/comment/reply/:commentId",
    title: "Get Replies",
    description: "Fetch all replies (nested comments) for a specific parent comment.",
    params: [{ name: "commentId", required: true, example: "clxxx123", hint: "Parent comment ID to get replies for." }],
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, parentCommentId, count, data: [{ id, userId, contentItemId, parentCommentId, body, isDeleted, createdAt, updatedAt, user, children }] }"],
  },
  {
    id: "catalog-comment-create-reply",
    group: "catalog-comments",
    method: "POST",
    path: "/api/catalog/comment/reply/:commentId",
    title: "Create Reply",
    description: "Reply to an existing comment. The parent comment must exist.",
    params: [{ name: "commentId", required: true, example: "clxxx123", hint: "Parent comment ID to reply to." }],
    body: {
      required: true,
      example: `{
  "userId": "clxxx456",
  "contentItemId": "clxxx789",
  "body": "Thanks for sharing your thoughts!"
}`,
      hint: "Required: userId, contentItemId, body. The commentId in URL becomes the parentCommentId.",
    },
    auth: "Requires API headers.",
    notes: ["Returns 404 if parent comment not found.", "Response: { success, source, path, parentCommentId, data: { id, userId, contentItemId, parentCommentId, body, isDeleted, createdAt, updatedAt } }"],
  },
  // Catalog - Categories
  {
    id: "catalog-category-list",
    group: "catalog-categories",
    method: "GET",
    path: "/api/catalog/category/all",
    title: "List Categories",
    description: "Fetch all content categories.",
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, count, data: [{ id, key, name, isActive, createdAt, updatedAt }] }"],
  },
  {
    id: "catalog-category-create",
    group: "catalog-categories",
    method: "POST",
    path: "/api/catalog/category/create",
    title: "Create Category",
    description: "Create a new category for content organization. The key is auto-generated from name (lowercase).",
    body: {
      required: true,
      example: `{
  "name": "K-Drama"
}`,
      hint: "Required: name. Optional: isActive (default: 1). Key auto-generated from name.",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, key, name, isActive, createdAt, updatedAt } }"],
  },
  {
    id: "catalog-category-update",
    group: "catalog-categories",
    method: "PUT",
    path: "/api/catalog/category/update/:id",
    title: "Update Category",
    description: "Update an existing category.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Category ID to update." }],
    body: {
      required: true,
      example: `{
  "name": "K-Drama Updated",
  "isActive": 1
}`,
      hint: "Fields: name, isActive. Key auto-updated from name.",
    },
    auth: "Requires API headers.",
    notes: ["Response: { message, updatedData: { id, key, name, isActive, createdAt, updatedAt } }"],
  },
  {
    id: "catalog-category-delete",
    group: "catalog-categories",
    method: "DELETE",
    path: "/api/catalog/category/delete/:id",
    title: "Delete Category",
    description: "Delete a category by id. This will cascade delete related content items.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Category ID to delete." }],
    auth: "Requires API headers.",
    notes: ["Response: { message, deletedData: { id, key, name, isActive, createdAt, updatedAt } }"],
  },
  // Catalog - Content Items
  {
    id: "catalog-content-item-list",
    group: "catalog-content-items",
    method: "GET",
    path: "/api/catalog/content-item/all",
    title: "List Content Items",
    description: "Fetch all content items with categories and units.",
    query: [
      { name: "providerKey", example: "dramabox", hint: "Filter by provider key (optional)." },
      { name: "sourceId", example: "12345", hint: "Filter by source id (optional)." },
    ],
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, count, data: [{ id, categoryId, providerKey, sourceId, isActive, category, units }] }"],
  },
  {
    id: "catalog-content-item-get",
    group: "catalog-content-items",
    method: "GET",
    path: "/api/catalog/content-item/:providerKey/:sourceId",
    title: "Get Content Item by Provider",
    description: "Fetch a single content item by provider key and source id with category and units.",
    params: [
      { name: "providerKey", required: true, example: "dramabox", hint: "Provider identifier (e.g., dramabox, melolo)." },
      { name: "sourceId", required: true, example: "12345", hint: "Source content identifier from provider." },
    ],
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, categoryId, providerKey, sourceId, isActive, category, units } }"],
  },
  {
    id: "catalog-content-item-create",
    group: "catalog-content-items",
    method: "POST",
    path: "/api/catalog/content-item/create",
    title: "Create Content Item",
    description: "Create a new content item linking provider content to a category.",
    body: {
      required: true,
      example: `{
  "categoryId": "clxxx123",
  "providerKey": "dramabox",
  "sourceId": "12345",
  "isActive": 1
}`,
      hint: "Required: categoryId, providerKey, sourceId. Optional: isActive (default: 1).",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, categoryId, providerKey, sourceId, isActive, createdAt, updatedAt } }"],
  },
  {
    id: "catalog-content-item-update",
    group: "catalog-content-items",
    method: "PUT",
    path: "/api/catalog/content-item/update/:id",
    title: "Update Content Item",
    description: "Update an existing content item.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Content item ID to update." }],
    body: {
      required: true,
      example: `{
  "categoryId": "clxxx456",
  "providerKey": "melolo",
  "sourceId": "67890",
  "isActive": 1
}`,
      hint: "Fields: categoryId, providerKey, sourceId, isActive. At least one field required.",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, categoryId, providerKey, sourceId, isActive, createdAt, updatedAt } }"],
  },
  {
    id: "catalog-content-item-delete",
    group: "catalog-content-items",
    method: "DELETE",
    path: "/api/catalog/content-item/delete/:id",
    title: "Delete Content Item",
    description: "Delete a content item by id. This will cascade delete related units and comments.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Content item ID to delete." }],
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, deletedId }"],
  },
  // Catalog - Content Units
  {
    id: "catalog-content-unit-list",
    group: "catalog-content-units",
    method: "GET",
    path: "/api/catalog/content-unit/all",
    title: "List Content Units",
    description: "Fetch all content units (episodes, chapters, movies) with their parent content items.",
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, count, data: [{ id, contentItemId, unitType, seasonNumber, unitNumber, title, durationSeconds, streamUrl, publishedAt, contentItem }] }"],
  },
  {
    id: "catalog-content-unit-create",
    group: "catalog-content-units",
    method: "POST",
    path: "/api/catalog/content-unit/create",
    title: "Create Content Unit",
    description: "Create a new content unit (episode/chapter/movie) for a content item.",
    body: {
      required: true,
      example: `{
  "contentItemId": "clxxx123",
  "unitType": "episode",
  "seasonNumber": 1,
  "unitNumber": 1,
  "title": "Pilot Episode",
  "durationSeconds": 3600,
  "streamUrl": "https://cdn.example.com/video.mp4",
  "publishedAt": "2024-01-15T00:00:00Z"
}`,
      hint: "Required: contentItemId, unitType (episode|chapter|movie), unitNumber. Optional: seasonNumber, title, durationSeconds, streamUrl, publishedAt.",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, contentItemId, unitType, seasonNumber, unitNumber, title, durationSeconds, streamUrl, publishedAt } }"],
  },
  {
    id: "catalog-content-unit-update",
    group: "catalog-content-units",
    method: "PUT",
    path: "/api/catalog/content-unit/update/:id",
    title: "Update Content Unit",
    description: "Update an existing content unit.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Content unit ID to update." }],
    body: {
      required: true,
      example: `{
  "unitType": "episode",
  "seasonNumber": 1,
  "unitNumber": 2,
  "title": "Episode 2",
  "durationSeconds": 3600,
  "streamUrl": "https://cdn.example.com/video2.mp4",
  "publishedAt": "2024-01-22T00:00:00Z"
}`,
      hint: "Fields: contentItemId, unitType, seasonNumber, unitNumber, title, durationSeconds, streamUrl, publishedAt. At least one field required.",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, contentItemId, unitType, seasonNumber, unitNumber, title, durationSeconds, streamUrl, publishedAt } }"],
  },
  {
    id: "catalog-content-unit-delete",
    group: "catalog-content-units",
    method: "DELETE",
    path: "/api/catalog/content-unit/delete/:id",
    title: "Delete Content Unit",
    description: "Delete a content unit by id.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Content unit ID to delete." }],
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, deletedId }"],
  },
  // Catalog - Favorites
  {
    id: "catalog-favorite-list",
    group: "catalog-favorites",
    method: "GET",
    path: "/api/catalog/favorite/all",
    title: "List Favorites",
    description: "Fetch all user favorites with content items and user details.",
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, count, data: [{ id, userId, contentItemId, createdAt, contentItem, user }] }"],
  },
  {
    id: "catalog-favorite-create",
    group: "catalog-favorites",
    method: "POST",
    path: "/api/catalog/favorite/create",
    title: "Create Favorite",
    description: "Add a content item to user favorites.",
    body: {
      required: true,
      example: `{
  "userId": "clxxx123",
  "contentItemId": "clxxx456"
}`,
      hint: "Required: userId, contentItemId. Unique constraint on (userId, contentItemId).",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, userId, contentItemId, createdAt } }"],
  },
  {
    id: "catalog-favorite-update",
    group: "catalog-favorites",
    method: "PUT",
    path: "/api/catalog/favorite/update/:id",
    title: "Update Favorite",
    description: "Update an existing favorite entry.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Favorite ID to update." }],
    body: {
      required: true,
      example: `{
  "userId": "clxxx456",
  "contentItemId": "clxxx789"
}`,
      hint: "Fields: userId, contentItemId. At least one field required.",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, userId, contentItemId, createdAt } }"],
  },
  {
    id: "catalog-favorite-delete",
    group: "catalog-favorites",
    method: "DELETE",
    path: "/api/catalog/favorite/delete/:id",
    title: "Delete Favorite",
    description: "Remove a favorite by id.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Favorite ID to delete." }],
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, deletedId }"],
  },
  // Catalog - Whitelist
  {
    id: "catalog-whitelist-list",
    group: "catalog-whitelist",
    method: "GET",
    path: "/api/catalog/whitelist/all",
    title: "List Whitelist",
    description: "Fetch all user category whitelists with category and user details.",
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, count, data: [{ id, userId, categoryId, createdAt, category, user }] }"],
  },
  {
    id: "catalog-whitelist-create",
    group: "catalog-whitelist",
    method: "POST",
    path: "/api/catalog/whitelist/create",
    title: "Create Whitelist Entry",
    description: "Add a category to user whitelist for access control.",
    body: {
      required: true,
      example: `{
  "userId": "clxxx123",
  "categoryId": "clxxx456"
}`,
      hint: "Required: userId, categoryId. Unique constraint on (userId, categoryId).",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, userId, categoryId, createdAt } }"],
  },
  {
    id: "catalog-whitelist-update",
    group: "catalog-whitelist",
    method: "PUT",
    path: "/api/catalog/whitelist/update/:id",
    title: "Update Whitelist Entry",
    description: "Update an existing whitelist entry.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Whitelist ID to update." }],
    body: {
      required: true,
      example: `{
  "userId": "clxxx456",
  "categoryId": "clxxx789"
}`,
      hint: "Fields: userId, categoryId. At least one field required.",
    },
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, data: { id, userId, categoryId, createdAt } }"],
  },
  {
    id: "catalog-whitelist-delete",
    group: "catalog-whitelist",
    method: "DELETE",
    path: "/api/catalog/whitelist/delete/:id",
    title: "Delete Whitelist Entry",
    description: "Remove a whitelist entry by id.",
    params: [{ name: "id", required: true, example: "clxxx123", hint: "Whitelist ID to delete." }],
    auth: "Requires API headers.",
    notes: ["Response: { success, source, path, deletedId }"],
  },
  // Drama V2 Endpoints
  {
    id: "drama-v2-recommendations",
    group: "drama-v2",
    method: "GET",
    path: "/api/v2/drama/recommendations",
    title: "Drama V2 Recommendations",
    description: "Combined trending recommendations from Dramabox and Melolo. Returns shuffled aggregated data.",
    query: [
      { name: "page", example: "1", value: "1", hint: "Page number for pagination. Default: 1" },
      { name: "limit", example: "15", value: "15", hint: "Items per page. Default: 15, Max: 50" },
      { name: "lang", example: "in", value: "in", hint: "Language code (in, en, es, pt, etc). Default: in" },
    ],
    notes: [
      "Cache: 5 minutes (short cache)",
      "Response: { success, source: 'dramabox/melolo', path, count, data: [{ id, title, description, coverImage, playCount, chapterCount, type }] }",
      "type: 1 = Dramabox, 2 = Melolo",
    ],
  },
  {
    id: "drama-v2-new-release",
    group: "drama-v2",
    method: "GET",
    path: "/api/v2/drama/new-release",
    title: "Drama V2 New Releases",
    description: "Combined new releases from Dramabox and Melolo providers.",
    query: [
      { name: "page", example: "1", value: "1", hint: "Page number for pagination. Default: 1" },
      { name: "limit", example: "15", value: "15", hint: "Items per page. Default: 15, Max: 50" },
      { name: "lang", example: "in", value: "in", hint: "Language code. Default: in" },
    ],
    notes: [
      "Cache: 5 minutes (short cache)",
      "Response format same as /recommendations",
    ],
  },
  {
    id: "drama-v2-search",
    group: "drama-v2",
    method: "GET",
    path: "/api/v2/drama/search",
    title: "Drama V2 Search",
    description: "Search dramas across both Dramabox and Melolo providers.",
    query: [
      { name: "query", required: true, example: "love", value: "love", hint: "Search keyword" },
      { name: "page", example: "1", value: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "15", value: "15", hint: "Items per page. Default: 15" },
      { name: "lang", example: "in", value: "in", hint: "Language code. Default: in" },
    ],
    notes: [
      "Cache: 5 minutes (short cache)",
      "Response: { success, source: 'dramabox/melolo', path, query, count, data: [...] }",
      "Results are NOT shuffled to maintain search relevance",
    ],
  },
  {
    id: "drama-v2-vip",
    group: "drama-v2",
    method: "GET",
    path: "/api/v2/drama/vip",
    title: "Drama V2 VIP Content",
    description: "VIP content from Dramabox. Melolo not supported.",
    query: [
      { name: "type", required: true, example: "1", value: "1", hint: "Provider type. Must be 1 (Dramabox)" },
      { name: "lang", example: "in", value: "in", hint: "Language code. Default: in" },
    ],
    notes: [
      "Cache: 1 hour (long cache)",
      "Response: { success, source: 'dramabox', path, type, count, data: [{ tabTitle, items: [{ id, title, description, coverImage, playCount, chapterCount }] }] }",
      "Error 404: 'VIP not available for Melolo' if type=2",
    ],
  },
  {
    id: "drama-v2-genre",
    group: "drama-v2",
    method: "GET",
    path: "/api/v2/drama/genre",
    title: "Drama V2 Genres",
    description: "List all available genres from Dramabox.",
    query: [
      { name: "page", example: "1", value: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "30", value: "30", hint: "Items per page. Default: 30" },
      { name: "lang", example: "in", value: "in", hint: "Language code. Default: in" },
    ],
    notes: [
      "Cache: 1 hour (long cache)",
      "Response: { success, source: 'dramabox', path, count, data: [{ genreId, genreName, lang }] }",
    ],
  },
  {
    id: "drama-v2-genre-detail",
    group: "drama-v2",
    method: "GET",
    path: "/api/v2/drama/genre/:id",
    title: "Drama V2 Genre Details",
    description: "Get dramas by genre ID. Dramabox only.",
    params: [{ name: "id", required: true, example: "1", hint: "Genre ID from /genre endpoint" }],
    query: [
      { name: "type", example: "1", value: "1", hint: "Provider type. Default: 1 (Dramabox)" },
      { name: "page", example: "1", value: "1", hint: "Page number. Default: 1" },
      { name: "limit", example: "15", value: "15", hint: "Items per page. Default: 15" },
      { name: "lang", example: "in", value: "in", hint: "Language code. Default: in" },
    ],
    notes: [
      "Cache: 5 minutes (short cache)",
      "Response: { success, source: 'dramabox', path, type, count, data: [{ id, title, description, coverImage, playCount, chapterCount }] }",
      "Error 404: 'Genre details not available for Melolo' if type=2",
    ],
  },
  {
    id: "drama-v2-detail",
    group: "drama-v2",
    method: "GET",
    path: "/api/v2/drama/detail/:id",
    title: "Drama V2 Details",
    description: "Get drama details by ID with chapter list.",
    params: [{ name: "id", required: true, example: "12345", hint: "Drama ID" }],
    query: [
      { name: "type", required: true, example: "1", value: "1", hint: "Provider type: 1=Dramabox, 2=Melolo" },
      { name: "lang", example: "in", value: "in", hint: "Language code. Default: in" },
    ],
    notes: [
      "No cache (dynamic content)",
      "Dramabox Response: { success, source: 'dramabox', path, type, chapterCount, data: { id, title, description, coverImage, playCount, chapterCount, chapters: [{ chapterId, chapterIndex }] } }",
      "Melolo Response: { success, source: 'melolo', path, type, chapterCount, data: { id, title, description, coverImage, playCount, chapterCount, chapters: [{ chapterId }] } }",
    ],
  },
  {
    id: "drama-v2-stream",
    group: "drama-v2",
    method: "GET",
    path: "/api/v2/drama/stream/:id/:chapterId",
    title: "Drama V2 Stream",
    description: "Get stream URL for a specific chapter by chapterId.",
    params: [
      { name: "id", required: true, example: "12345", hint: "Drama ID" },
      { name: "chapterId", required: true, example: "ch001", hint: "Chapter ID from detail endpoint" },
    ],
    query: [
      { name: "type", required: true, example: "1", value: "1", hint: "Provider type: 1=Dramabox, 2=Melolo" },
      { name: "lang", example: "in", value: "in", hint: "Language code. Default: in" },
    ],
    notes: [
      "No cache (dynamic content)",
      "For Dramabox: uses chapterId to find chapter index internally",
      "Dramabox Response: { success, source: 'dramabox', path, type, data: { id, coverImage, chapterId, streamUrl, qualities: [{ quality, streamUrl }] } }",
      "Melolo Response: { success, source: 'melolo', path, type, data: { id, coverImage, chapterId, streamUrl, qualities: [{ quality, streamUrl }] } }",
    ],
  },
  {
    id: "drama-v2-batch-download",
    group: "drama-v2",
    method: "GET",
    path: "/api/v2/drama/get-all-chapters/:id",
    title: "Drama V2 Batch Download",
    description: "Get all chapters with stream URLs for batch download. Dramabox only.",
    params: [{ name: "id", required: true, example: "12345", hint: "Drama ID" }],
    query: [
      { name: "type", required: true, example: "1", value: "1", hint: "Provider type. Must be 1 (Dramabox)" },
      { name: "lang", example: "in", value: "in", hint: "Language code. Default: in" },
    ],
    notes: [
      "No cache (dynamic content)",
      "Response: { success, source: 'dramabox', path, type, count, data: [{ chapterId, chapterIndex, chapterName, streamUrl }] }",
      "Error 404: 'Batch download not available for Melolo' if type=2",
      "This endpoint may take longer due to batch fetching",
    ],
  },
  {
    id: "movie-private-recommendations",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/recommendations",
    title: "Private Recommendations",
    description: "Get movie recommendations for you.",
    uiHidden: true,
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
    notes: ["Response: { success, source, path, count, data: [{ id, title, coverImage, detailPath }] }"],
  },
  {
    id: "movie-private-new-release",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/new-release",
    title: "Private New Releases",
    description: "Get latest movie releases.",
    uiHidden: true,
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
  },
  {
    id: "movie-private-rank",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/rank",
    title: "Private Movie Ranking",
    description: "Get hottest movies ranking.",
    uiHidden: true,
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
  },
  {
    id: "movie-private-genre",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/genre",
    title: "Private Movie Genres",
    description: "Get list of movie genres.",
    uiHidden: true,
  },
  {
    id: "movie-private-country",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/country",
    title: "Private Movie Countries",
    description: "Get list of movie countries.",
    uiHidden: true,
  },
  {
    id: "movie-private-genre-detail",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/genre/:id",
    title: "Private Movies by Genre",
    description: "Get movies filtered by genre ID.",
    uiHidden: true,
    params: [{ name: "id", required: true, hint: "Genre name (e.g., Action)" }],
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
  },
  {
    id: "movie-private-country-detail",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/country/:id",
    title: "Private Movies by Country",
    description: "Get movies filtered by country name.",
    uiHidden: true,
    params: [{ name: "id", required: true, hint: "Country name (e.g., Korea)" }],
    query: [
      { name: "page", example: "1", value: "1" },
      { name: "limit", example: "28", value: "28" },
    ],
  },
  {
    id: "movie-private-detail",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/detail/:detailPath",
    title: "Private Movie Details",
    description: "Get full movie details including casts and genre.",
    uiHidden: true,
    params: [{ name: "detailPath", required: true, hint: "Detailed path from list." }],
    notes: ["Response: { success, source, data: { id, title, description, coverImage, detailPath, casts: [], genres: [], episodes: [] } }"],
  },
  {
    id: "movie-private-stream",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/stream/:subjectId/:detailPath",
    title: "Private Movie Streaming",
    description: "Get stream URLs for a specific movie.",
    uiHidden: true,
    params: [
      { name: "subjectId", required: true, hint: "Subject ID from detail." },
      { name: "detailPath", required: true, hint: "Detail path from detail." },
    ],
    notes: ["Response: { success, source, data: { streamUrl, qualities: [], subtitles: [] } }"],
  },
  {
    id: "movie-private-captions",
    group: "movie-private",
    method: "GET",
    path: "/api/movies/private/captions/:subtitleId/:subjectId/:detailPath/:format",
    title: "Private Movie Captions",
    description: "Get captions/subtitles for the stream.",
    uiHidden: true,
    params: [
      { name: "subtitleId", required: true },
      { name: "subjectId", required: true },
      { name: "detailPath", required: true },
      { name: "format", required: true, example: "vtt" },
    ],
  },
]
